name: CI

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1


jobs:

  test:
    name: 'Test with python ${{ matrix.python-version }} on ${{ matrix.os }}'
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', 'pypy3.7', 'pypy3.8', 'pypy3.9']
        include:
          - os: windows-latest
            python-version: '3.7'

    steps:

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install python'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: 'Install hatch'
        run: |
          python -m pip install --upgrade hatch

      - name: 'Run tests'
        run: >
          hatch run +py=${{ matrix.python-version }} ci:cov
          --data-file '.coverage.${{ matrix.os }}.${{ matrix.python-version }}'

      - name: 'Upload coverage'
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: '.coverage.*'
          if-no-files-found: error
          retention-days: 30


  coverage:
    if: github.repository == 'jamielinux/leapseconds' && github.ref == 'refs/heads/main'
    name: 'Generate code coverage badge'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: test

    steps:

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 'Install hatch'
        run: |
          python -m pip install --upgrade hatch

      - name: 'Download coverage'
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: 'Combine coverage'
        run: |
          hatch run +py=3.11 ci:cov-combine
          export TOTAL=$(python -c \
              "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
          echo "total=$TOTAL" >> $GITHUB_ENV
          echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY

      - name: 'Coverage badge'
        uses: schneegans/dynamic-badges-action@5d424ad4060f866e4d1dab8f8da0456e6b1c4f56  # v1.6.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 7c0026bdbd4a00863dcd6878e5e3b943
          filename: leapseconds.covbadge.json
          label: coverage
          message: ${{ env.total }}%
          minColorRange: 70
          maxColorRange: 90
          valColorRange: ${{ env.total }}
