name: Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1


jobs:

  build:
    if: github.repository == 'jamielinux/leapseconds'
    name: 'Build'
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade build

      - name: 'Build'
        run: |
          python -m build

      - name: 'Upload dist'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: 'dist/*'
          if-no-files-found: error
          retention-days: 30


  publish:
    if: github.repository == 'jamielinux/leapseconds'
    name: 'Publish to PyPI'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: 'Download dist'
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: 'Publish'
        uses: pypa/gh-action-pypi-publish@48b317d84d5f59668bb13be49d1697e36b3ad009  # v1.8.3
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
